# Generated by Django 3.1.2 on 2020-10-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='descripcion_corta',
            field=models.TextField(default='descripcion_corta', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animes.autor'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animes.animegen'),
        ),
    ]
