# Generated by Django 3.1.2 on 2020-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_auto_20201026_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='imagen_fondo',
            field=models.ImageField(default=3, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='descripcion_corta',
            field=models.TextField(max_length=500),
        ),
    ]
